// Generated by https://quicktype.io
import { User } from "./req-user-response-interface";
export interface CheckTokenResponse {
    HEADER_token:   HEADER_token;
    RESPONSE: Response; 
}

export interface HEADER_token {
    CODE:          number;
    CODE_RESPONSE: string;
    MESSAGE:       string;
}

export interface Response {
    token: string;
    fecha_expiracion:string,
    user:     User;
}
