// Generated by https://quicktype.io

export interface ResponsePost {
    HEADER:   Header;
    RESPONSE: null;
}

export interface Header {
    CODE:          number;
    CODE_RESPONSE: string;
    MESSAGE:       string;
}
