// Generated by https://quicktype.io

export interface EventoResponseeeee {
    HEADER:   Header;
    RESPONSE: Response[];
}

export interface Header {
    CODE:          number;
    CODE_RESPONSE: string;
    MESSAGE:       string;
}

export interface Response {
    evento:      Evento;
    estaEnRango: boolean;
}

export interface Evento {
    esfavorito:   number;
    favorito:     null;
    HoraInicio:   string;
    HoraFinal:    string;
    FechaInicio:  string;
    ideventos:    number;
    titulo:       string;
    NombreLocal:  string;
    urlFuente:    string;
    url:          string;
    Monto:        number;
    Destacado:    number;
    categoria_id: number;
    EsGratis:     string;
    Distrito:     string;
    estado:       null;
    idfecha:      number;
    usuario_id:   number;
}
