// Generated by https://quicktype.io

export interface CategoriaResponse {
    HEADER:   Header;
    RESPONSE: Categoria[];
}

export interface Header {
    CODE:          number;
    CODE_RESPONSE: string;
    MESSAGE:       Message[];
}

export interface Message {
    msg: string;
}

export interface Categoria {
    cantidad:        number | null;
    idCategorias:    number;
    nombreCategoria: string;
    estado:          number;
    iconos:          null | string;
}
